#!/bin/bash -ex

HOSTNAME=newznabapp
USERNAME=nzb
GROUPNAME=www-data

####################################################
# INSTALL ACESHOME UTILITIES
####################################################
git clone git://github.com/tssgery/aceshome.git /opt/aceshome

# set hostname
echo "$HOSTNAME" > /etc/hostname
sed -i "s|127.0.1.1 \(.*\)|127.0.1.1 $HOSTNAME|" /etc/hosts

# create the nzb userid (which all the nzb daemons run as)
# groupadd $GROUPNAME
useradd -c "NZB App userid" -d /home/$USERNAME -g $GROUPNAME -m -s /bin/bash "$USERNAME"
chown -R $USERNAME:$GROUPNAME /home/$USERNAME

# hold the udev package due to a bug (no longer needed)
# echo udev hold | dpkg --set-selections

# add the python installation tools and sudo
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get -y \
    -o DPkg::Options::=--force-confdef \
    -o DPkg::Options::=--force-confold \
    install python-software-properties sudo subversion 

/opt/aceshome/bin/makeunrar

/opt/aceshome/bin/makemedia

####################################################
# install newznab pre-reqs
####################################################
DEBIAN_FRONTEND=noninteractive apt-get -y \
    -o DPkg::Options::=--force-confdef \
    -o DPkg::Options::=--force-confold \
    install \
    php5-cli libgd2-xpm php-pear php5-curl php5-gd

####################################################
# pull down newznab
####################################################
cd /home/$USERNAME
wget http://www.newznab.com/newznab-0.2.3.zip
unzip newznab-0.2.3.zip
rm newznab-0.2.3.zip
ln -s /home/$USERNAME/newznab-0.2.3 /home/$USERNAME/newznab
# make the newznab temp directory
mkdir /home/$USERNAME/tmp

mv /home/$USERNAME/config/misc/update_scripts/cron_scripts/* /home/$USERNAME/newznab/misc/update_scripts/cron_scripts


# set it to start on boot
update-rc.d newznab defaults

# setup the apache2 default site to be newznab
sed -i "s|DocumentRoot /var/www|DocumentRoot /home/nzb/newznab/www|g" /etc/apache2/sites-available/default
sed -i "s|<Directory /var/www/>|<Directory /home/nzb/newznab/www/>|g"    /etc/apache2/sites-available/default

# apache2
a2enmod rewrite

sed -i "s|Web:    |Newznab:|" /etc/confconsole/services.txt

####################################################
# Final tasks
####################################################
# fixup the mysqld config file
sed -i "s|^\[mysqld\]|\[mysqld\]\ngroup_concat_max_len=8192|" /etc/mysql/my.cnf

# add nzb to sudoers file
echo "# Adding nzb to sudoers list" >> /etc/sudoers
echo "$USERNAME    ALL=(ALL) ALL"   >> /etc/sudoers.d/nzb
chmod 0440 /etc/sudoers.d/nzb

chown -R $USERNAME:$GROUPNAME /home/$USERNAME
chmod -R 774 /home/$USERNAME/newznab-0.2.3/

####################################################
# done!
####################################################
exit




